Task-48314 : implement no more kudos left  pop-up
Meeds-io/kudos pull request #99
Opened 2021-09-28 19:06 UTC by nidhalnidhal

implement a pop-up that has to be displayed when there is no more kudos left

2021-09-29 08:44 UTC, aelbenney commented on kudos-webapps/src/main/webapp/vue-app/kudos/components/KudosApp.vue
> +          const alertMessage = this.NoKudosLeftAlert.replace('{0}', this.numberOfKudosAllowed).replace('{1}' , this.kudosPeriodType);
We can put the `NoKudosLeftAlert` in a computed variable.

2021-09-29 09:48 UTC, boubaker requested changes, later dismissed

2021-09-29 09:48 UTC, boubaker commented on kudos-webapps/src/main/webapp/vue-app/kudos/components/KudosApp.vue
> +      NoKudosLeftAlert: this.$t('exoplatform.kudos.info.noKudosLeft'),
```suggestion
```

2021-09-29 09:48 UTC, boubaker commented on kudos-webapps/src/main/webapp/vue-app/kudos/components/KudosApp.vue
> +          const alertMessage = this.NoKudosLeftAlert.replace('{0}', this.numberOfKudosAllowed).replace('{1}' , this.kudosPeriodType);
```suggestion
          const alertMessage = this.$t('exoplatform.kudos.info.noKudosLeft', {0: this.numberOfKudosAllowed, 1: this.kudosPeriodType});
```

2021-09-30 14:05 UTC, aelbenney approved these changes

2021-09-30 14:11 UTC, merged